export const data = [
    {
        id:1,
        header:"Kalp ve damar hastalıkları risk yönetimi",
        text:"Kalp ve damar hastalıkları halen tüm dünyada sağlık sorunlarının ve ölümün birinci sırasındaki sebebidir ve sıklığı giderek artmaktadır.Bu hastalıkların oluşumuna ve ilerlemesine neden olabilecek birçok risk faktörü tespit edilmiş olmakla birlikte en güçlü risk faktörleri ileri yaş, ailesel yatkınlık, hareketsiz yaşam tarzı, beslenme bozukluğu, şişmanlık, hipertansiyon, şeker hastalığı, kan yağları dengesinde bozukluk, sigara kullanımı ve anksiyete, depresyon gibi psikiyatrik bozukluklardır.Kalp hastalığı oluşmadan alınan tedbirler birincil kardiyovasküler koruma, kalp hastalığı gelişenlerde ise hastalığın ilerlemesinin önlenmesi ve iyileşme sürecinin hızlandırılması için olan tedavi ve yaşam tarzının uygun hale getirilmesi ikincil kardiyovasküler koruma (kardiyak rehabilitasyon) olarak tanımlanır. Her iki yaklaşımda da öncelik risk faktörlerinin kontrol altına alınmasıdır.Fizik, kondüsyon ve sağlık durumuna göre kişiye özel planlanmış beslenme önerileri ve egzersiz, gerekli durumlarda ilaç tedavisi, sigarayı bıraktırma ve psikoterapi uygulamaları kardiyovasküler korumanın ana bileşenlerini oluşturmaktadır."
    },
    {
        id:2,
        header:"Yoga pratiğinin kardiyovasküler risk faktörlerine olan etkilerini araştıran çalışmaların değerlendirilmesi.",
        text:"Vücut ağırlığından bağımsız olarak hareketsiz yaşam tarzı kalp damar hastalığı oluşumunda ve ilerlemesinde önemli bir risk faktördür. Fiziksel aktivitenin artırılmasının kalp hastalığı riskini azalttığı bilinmektedir. Egzersizin ise risk azalmasına ek faydalarının olabileceği ve artan kanıtlar egzersizin stres ilişkili sinir ve hormon aktivitelerini azaltarak fiziksel ve zihinsel sağlığa fayda sağladığı inancını desteklemektedir.3 Bu hipotezi araştıran birçok çalışma kalp hastalıklarının önlemesinde ve hastalıkların iyileşme sürecinin hızlanmasında egzersiz uygulamalarının etkinliğini kanıtlanmıştır.Klinik çalışmaların meta analizleri ve sistematik incelemeleri yoga uygulamalarının depresyon ve anksiyete bozukluğu semptomlarını iyileştirebileceğini göstermiştir. Tek başına veya diğer tedavilere yardımcı olarak kullanılan farkındalık temelli meditasyonun depresyon üzerinde olumlu etkileri vardır ve etkileri altı ay veya daha fazla sürebilir. Anksiyete bozukluğu olan kişilerde pozitif bulgular daha zayıf olsa da, yardımcı bir yöntem olarak yoga anksiyete bozukluklarının, özellikle panik bozukluğunun tedavisini kolaylaştırır"
    },
    {
        id:3,
        header:"Yoga pratiğinin kalp damar hastalıklarına etkilerini araştıran çalışmaların değerlendirilmesi.",
        text:"Kalp krizi geçirenlerde yoga tabanlı kardiyak rehabilitasyon ile eğitim tavsiyesi içeren gelişmiş standart bakımın karşılaştırıldığı çalışmada; yoga tabanlı kardiyak rehabilitasyon grubundaki hastaların kriz öncesi aktivitelere daha fazla geri döndüğü, kalp krizi sonrası komplikasyonlar, sigarayı bırakma ve tedavi uyumu açısından ise benzer sonuçların elde edildiği görüldü. Sonuç olarak yoganın geleneksel kardiyak rehabilitasyon altyapısının olmadığı veya geleneksek kardiyak rahabilitasyona uygun olmayanlar için alternatif bir seçenek olabileceği vurgulandı.Kalp yetmezliği hafif fonksiyonel kapasite azalmasından yatalak olma durumuna kadar çok farlı klinik sonuçlar ortaya çıkarabileceğinden kalp yetmezliği olan hastalar egzersiz temelli rehabilitasyon programlarına uyum sağlayamayabilirler. Yoga nefes egzersizleri bu tür hastalarda daha ön planda düşünülebilir. Yapılan klinik çalışmada yoga gevşeme teknikleri sayesinde, kronik kalp yetmezliğinde nefes alma hızının yavaşlattığı, nefes darlığını azalttığı ve bildirildiğine göre akciğer gaz alışverişinde ve egzersiz performansında bir iyileşme sağladığı ortaya konulmuştur"
    },
   
]